-- ============================================================
-- Migration 20260714: Contact change requests (dual-channel
-- Change Email / Change Phone flows with fallback recovery)
-- Project: Smartclaz
-- Safe to re-run — all statements use IF NOT EXISTS.
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- CONTACT CHANGE REQUESTS
-- One row per in-flight (or completed/expired/cancelled) email
-- or phone change attempt. OTP codes here are self-contained
-- 6-digit codes generated by the API routes — they never touch
-- Supabase Auth's signInWithOtp/verifyOtp primitives, so the
-- tutor's active session is never disturbed mid-flow.
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS contact_change_requests (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tutor_id            uuid        REFERENCES tutors(id),
  change_type         text        NOT NULL,
  -- 'email' | 'phone'
  old_value           text        NOT NULL,
  new_value           text        NOT NULL,
  status              text        DEFAULT 'pending_old_otp',
  -- pending_old_otp | pending_new_otp | completed | expired | cancelled | support_review
  old_otp_code        text,
  old_otp_sent_at     timestamptz,
  old_otp_verified_at timestamptz,
  old_otp_attempts    int         DEFAULT 0,
  new_otp_code        text,
  new_otp_sent_at     timestamptz,
  new_otp_verified_at timestamptz,
  new_otp_attempts    int         DEFAULT 0,
  used_fallback       boolean     DEFAULT false,
  fallback_channel    text,
  -- 'phone' | 'email'
  ip_address          text,
  -- SHA-256 hashed, never raw (matches lib/rateLimit.ts convention)
  user_agent          text,
  expires_at          timestamptz DEFAULT (now() + interval '30 minutes'),
  created_at          timestamptz DEFAULT now(),
  completed_at        timestamptz
);

CREATE INDEX IF NOT EXISTS idx_contact_change_tutor
  ON contact_change_requests (tutor_id, status);

-- ────────────────────────────────────────────────────────────
-- RLS — deny-all for anon/authenticated
-- No policy is defined on purpose (matches otp_attempts /
-- rate_limits convention in migration 001). Accessed exclusively
-- via SUPABASE_SERVICE_ROLE_KEY from API routes, which bypasses
-- RLS entirely.
-- ────────────────────────────────────────────────────────────
ALTER TABLE contact_change_requests ENABLE ROW LEVEL SECURITY;

-- 📝 NOTE: No CREATE POLICY statement here on purpose — Postgres has no
-- `CREATE POLICY IF NOT EXISTS`. If a policy is ever added to this table in a
-- future migration, guard it with:
--   DO $$ BEGIN
--     IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public'
--       AND tablename='contact_change_requests' AND policyname='<name>') THEN
--       CREATE POLICY <name> ON contact_change_requests ...;
--     END IF;
--   END $$;
-- (see migration 001 for the same pattern applied to storage.objects)

-- ────────────────────────────────────────────────────────────
-- SUPPORT REQUESTS — extend for authenticated "still logged in
-- but can't complete OTP" recovery case (lighter-weight than the
-- existing public support-recovery flow, which is for tutors who
-- are fully logged out).
-- ────────────────────────────────────────────────────────────
ALTER TABLE support_requests
  ADD COLUMN IF NOT EXISTS tutor_id    uuid REFERENCES tutors(id),
  ADD COLUMN IF NOT EXISTS change_type text;

COMMENT ON COLUMN support_requests.tutor_id IS
  'Set only for the authenticated contact-change support recovery flow (app/api/auth/contact-change/support-recovery). NULL for the existing public/logged-out recovery flow.';
COMMENT ON COLUMN support_requests.change_type IS
  'email | phone — only set when tutor_id is set.';
